version: 2

jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Deploying website.
          command: echo Deploying website.

  deploy:
  
    docker:
      - image: cibuilds/aws

    steps:
    - attach_workspace:
          at: ~/website

      - run:
          name: deploy to AWS
          command: |
            ls
            cd src/website
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
               aws s3 sync . s3://stepanvalchyshyn.com/ --delete
            else
               echo "Not master branch, dry run only"
            fi

workflows:
  version: 2

  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master