version: 2

working_directory: ~/

jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Deploying website.
          command: echo Deploying website.

  deploy:

    docker:
      - image: cibuilds/aws

    steps:
      - attach_workspace:
          at: ~/

      - run:
        name: Deploy to S3 if branch is Master.
          command:
              aws s3 sync ~/ s3://stepanvalchyshyn.com/ --delete

  workflows:
  version: 2

  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master