version: 2

working_directory: ~/

jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Deploying website.
          command: echo Deploying website.

  deploy:
    docker:
      - image: cibuilds/aws

    steps:
      - attach_workspace:
          at: ~/

      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
          aws s3 sync ~/ s3://stepanvalchyshyn.com/ --delete
          fi