version: 2

working_directory: ~/

jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Deploying website.
          command: echo Deploying website.

  deploy:
    docker:
      - image: cibuilds/aws

          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync src/website/
              s3://stepanvalchyshyn.com/ --delete
            else
              echo "Not master branch, dry run only"
            fi